[package]
name = "sprite-info"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3"
rayon = "1.7"
image = "0.24"
serde_yaml = "0.9"
serde_json = "1.0"
serde = { version = "1", features = ["derive"] }
