name: Publish Stitch Website

on:
  workflow_dispatch:
  push:
    tags:
      - "@bscotch/stitch-site@*"
  schedule:
    # https://crontab.guru/#22_13,17,20,22_*_*_1-5
    - cron: '22 13,17,20,22 * * 1-5'

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - run: npm run setup:pnpm

      - name: Install Dependencies
        run: pnpm install --filter=@bscotch/gamemaker-releases... --filter=@bscotch/stitch-site...

      - name: Update Unified Feed
        run: pnpm node scripts/update-unified-feed.mjs
        working-directory: packages/site

      - name: Build
        run: pnpm turbo run build --filter=@bscotch/stitch-site... --filter=@bscotch/gamemaker-releases...

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1.0.9
        with:
          path: packages/site/build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
        
